#!/usr/bin/env python3
import itertools
import subprocess
import sys


def read_file(path):
    def options():
        with open(path) as f:
            for line in itertools.islice(f, 1, None):
                if not line.startswith('#'):
                    return
                k, v = line[1:].split('=')
                yield k.strip(), v.strip()
    return dict(options())


def main():
    target = sys.argv[1]
    options = read_file(target)
    command = '%s %s' % (options['command'], target)
    subprocess.call(['nix-shell', '--command', command,
                     '-p'] + options['packages'].split())


if __name__ == '__main__':
    main()
